# Clide 代理設定範例：可複製為 config/agents.toml 後依需求調整。

default_profile = "local-stub"

[[profiles]]
id = "local-stub"
label = "Python 範例代理"
description = "透過內建 python 腳本示範 JSON IPC"

[profiles.transport]
kind = "local_process"
program = "python3"
args = ["python/agent_stub.py"]

[[profiles]]
id = "openai-codex"
label = "OpenAI/Codex"
description = "使用 OpenAI Chat Completions API 進行分析"

[profiles.transport]
kind = "http_api"
provider = "open_ai"
api_key_env = "OPENAI_API_KEY"
model = "gpt-4o-mini"
system_prompt = "你是一名資深程式設計助理，請針對提供的原始碼提出改善建議。"

[[profiles]]
id = "gemini"
label = "Google Gemini"
description = "透過 Gemini API 提供即時建議"

[profiles.transport]
kind = "http_api"
provider = "gemini"
api_key_env = "GEMINI_API_KEY"
model = "gemini-1.5-flash"

[[profiles]]
id = "ollama-local"
label = "Ollama 本地模型"
description = "連線至本地 Ollama 服務 (預設 http://localhost:11434)"

[profiles.transport]
kind = "http_api"
provider = "ollama"
model = "llama3"

[[profiles]]
id = "mcp-tools"
label = "MCP 工具"
description = "透過 MCP 端點呼叫自訂工具"

[profiles.transport]
kind = "mcp"
endpoint = "http://localhost:8081/invoke"
tool = "code_search"
