# config/log4rs.yaml
appenders:
  file:
    kind: rolling_file
    path: "logs/clide.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} - {l} - {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10 mb
      roller:
        kind: fixed_window
        base: 1
        count: 5
        pattern: "logs/clide.log.{}.gz"

root:
  level: info
  appenders:
    - file
