name: Build

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install Windows target
        run: rustup target add x86_64-pc-windows-gnu
      - name: Install cross toolchain
        run: sudo apt-get update && sudo apt-get install -y mingw-w64
      - name: Build debug targets
        run: cargo run --bin dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: clide-debug-linux-gnu
          path: |
            dist/Clide-debug
            dist/Clide-debug.exe

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build Windows debug
        run: cargo build
      - name: Prepare artifact
        run: |
          New-Item -ItemType Directory -Force -Path dist
          Copy-Item target\\debug\\clide.exe dist\\Clide-debug.exe
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: clide-debug-windows-msvc
          path: dist\\Clide-debug.exe
